<?php

return [
    'frontend_read_only' => filter_var(env('FHIR_FRONTEND_READ_ONLY', true), FILTER_VALIDATE_BOOLEAN),
    'lesion_viewer_source' => env('FHIR_LESION_VIEWER_SOURCE', 'mock'),
    'controlled_ingestion_prototype' => [
        'enabled' => filter_var(env('FHIR_CONTROLLED_INGESTION_PROTOTYPE_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
        'mode' => env('FHIR_CONTROLLED_INGESTION_PROTOTYPE_MODE', 'mock'),
        'allow_fhir_write' => false,
    ],
    'gateway_report_only' => filter_var(env('FHIR_GATEWAY_REPORT_ONLY', true), FILTER_VALIDATE_BOOLEAN),
    'gateway_enforce_read' => filter_var(env('FHIR_GATEWAY_ENFORCE_READ', false), FILTER_VALIDATE_BOOLEAN),
    'gateway_enforce_write' => filter_var(env('FHIR_GATEWAY_ENFORCE_WRITE', false), FILTER_VALIDATE_BOOLEAN),
    'gateway_enforce_medication_request_write' => filter_var(env('FHIR_GATEWAY_ENFORCE_MEDICATION_REQUEST_WRITE', false), FILTER_VALIDATE_BOOLEAN),
    'policy_decision_store' => env('FHIR_POLICY_DECISION_STORE', 'both'),
    'gateway_enforce_diagnostic_report_read' => filter_var(env('FHIR_GATEWAY_ENFORCE_DIAGNOSTIC_REPORT_READ', false), FILTER_VALIDATE_BOOLEAN),
    'gateway_enforce_document_reference_read' => filter_var(env('FHIR_GATEWAY_ENFORCE_DOCUMENT_REFERENCE_READ', false), FILTER_VALIDATE_BOOLEAN),
    'gateway_enforce_medication_request_read' => filter_var(env('FHIR_GATEWAY_ENFORCE_MEDICATION_REQUEST_READ', false), FILTER_VALIDATE_BOOLEAN),
    'allow_dev_practitioner_fallback' => filter_var(env('FHIR_ALLOW_DEV_PRACTITIONER_FALLBACK', false), FILTER_VALIDATE_BOOLEAN),
    'dev_practitioner_reference' => env('FHIR_DEV_PRACTITIONER_REFERENCE', 'Practitioner/practitioner-001'),
    'document_storage_driver' => env('FHIR_DOCUMENT_STORAGE_DRIVER', 'dev_fixture'),
    'document_scan_driver' => env('FHIR_DOCUMENT_SCAN_DRIVER', 'dev_placeholder'),
    'document_scan_timeout_seconds' => (int) env('FHIR_DOCUMENT_SCAN_TIMEOUT_SECONDS', 10),
    'document_scan_retry_count' => (int) env('FHIR_DOCUMENT_SCAN_RETRY_COUNT', 0),
    'document_scan_fail_closed' => filter_var(env('FHIR_DOCUMENT_SCAN_FAIL_CLOSED', true), FILTER_VALIDATE_BOOLEAN),
    'document_audit_store' => env('FHIR_DOCUMENT_AUDIT_STORE', 'log'),
    'document_scan_failed_rate_threshold' => (float) env('FHIR_DOCUMENT_SCAN_FAILED_RATE_THRESHOLD', 0.1),
    'document_quarantine_backlog_threshold' => (int) env('FHIR_DOCUMENT_QUARANTINE_BACKLOG_THRESHOLD', 10),
    'document_oldest_quarantine_minutes_threshold' => (int) env('FHIR_DOCUMENT_OLDEST_QUARANTINE_MINUTES_THRESHOLD', 60),
    'clamav_host' => env('FHIR_CLAMAV_HOST', '127.0.0.1'),
    'clamav_port' => (int) env('FHIR_CLAMAV_PORT', 3310),
    'clamav_timeout_seconds' => (int) env('FHIR_CLAMAV_TIMEOUT_SECONDS', 10),
    'clamav_max_chunk_bytes' => (int) env('FHIR_CLAMAV_MAX_CHUNK_BYTES', 8192),
    'document_delete_endpoint_enabled' => filter_var(env('FHIR_DOCUMENT_DELETE_ENDPOINT_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    'document_purge_enabled' => filter_var(env('FHIR_DOCUMENT_PURGE_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    'document_retention_days' => (int) env('FHIR_DOCUMENT_RETENTION_DAYS', 30),
    'document_quarantine_retention_hours' => (int) env('FHIR_DOCUMENT_QUARANTINE_RETENTION_HOURS', 24),
    'document_quarantine_cleanup_enabled' => filter_var(env('FHIR_DOCUMENT_QUARANTINE_CLEANUP_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    'document_upload_max_bytes' => (int) env('FHIR_DOCUMENT_UPLOAD_MAX_BYTES', 10 * 1024 * 1024),
    'document_upload_allowed_content_types' => [
        'application/pdf',
        'image/png',
        'image/jpeg',
        'text/plain',
    ],
    'cds' => [
        'execution_gate_enabled' => filter_var(env('FHIR_CDS_EXECUTION_GATE_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
        'runtime_actions_enabled' => filter_var(env('FHIR_CDS_RUNTIME_ACTIONS_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
        'emergency_disable_all_cds' => filter_var(env('FHIR_CDS_EMERGENCY_DISABLE_ALL_CDS', true), FILTER_VALIDATE_BOOLEAN),
        'allow_advisory_mode' => filter_var(env('FHIR_CDS_ALLOW_ADVISORY_MODE', false), FILTER_VALIDATE_BOOLEAN),
        'allow_blocking_mode' => filter_var(env('FHIR_CDS_ALLOW_BLOCKING_MODE', false), FILTER_VALIDATE_BOOLEAN),
        'allow_clinical_inference' => filter_var(env('FHIR_CDS_ALLOW_CLINICAL_INFERENCE', false), FILTER_VALIDATE_BOOLEAN),
        'allow_drug_interaction' => filter_var(env('FHIR_CDS_ALLOW_DRUG_INTERACTION', false), FILTER_VALIDATE_BOOLEAN),
        'allow_dose_safety' => filter_var(env('FHIR_CDS_ALLOW_DOSE_SAFETY', false), FILTER_VALIDATE_BOOLEAN),
        'allow_purge' => filter_var(env('FHIR_CDS_ALLOW_PURGE', false), FILTER_VALIDATE_BOOLEAN),
        'completeness_rules' => [
            'cds.completeness.medication_request.missing_status.v1' => ['status' => 'active'],
            'cds.completeness.medication_request.missing_intent.v1' => ['status' => 'active'],
            'cds.completeness.medication_request.missing_subject.v1' => ['status' => 'active'],
            'cds.completeness.medication_request.missing_requester.v1' => ['status' => 'active'],
            'cds.completeness.medication_request.missing_dosage_instruction.v1' => ['status' => 'active'],
            'cds.completeness.medication_request.missing_dispense_request.v1' => ['status' => 'active'],
            'cds.completeness.medication_request.missing_medication_code_or_display.v1' => ['status' => 'active'],
            'cds.completeness.observation.missing_status.v1' => ['status' => 'active'],
            'cds.completeness.observation.missing_code.v1' => ['status' => 'active'],
            'cds.completeness.observation.missing_subject.v1' => ['status' => 'active'],
            'cds.completeness.observation.missing_effective_datetime.v1' => ['status' => 'active'],
            'cds.completeness.observation.missing_value_or_component.v1' => ['status' => 'active'],
            'cds.completeness.observation.missing_unit.v1' => ['status' => 'active'],
            'cds.completeness.condition.missing_clinical_status.v1' => ['status' => 'active'],
            'cds.completeness.condition.missing_verification_status.v1' => ['status' => 'active'],
            'cds.completeness.condition.missing_code.v1' => ['status' => 'active'],
            'cds.completeness.condition.missing_subject.v1' => ['status' => 'active'],
            'cds.completeness.condition.missing_onset_or_recorded_date.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_status.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_type.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_category.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_subject.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_date.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_content_attachment.v1' => ['status' => 'active'],
            'cds.completeness.document_reference.missing_attachment_metadata.v1' => ['status' => 'active'],
        ],
    ],
];
